---
runtime:
  threads: ~
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
language: en-US
theme: dark
roots:
  - path: /home/niscolas/.local/share/Steam
    store: steam
  - path: /home/niscolas/.var/app/com.valvesoftware.Steam/.local/share/Steam
    store: steam
  - path: /home/niscolas/.config/heroic
    store: heroic
  - path: /home/niscolas/.config/lutris
    store: lutris
  - path: /mnt/storage/SteamLibrary
    store: steam
  - path: /home/niscolas/.local/share/Steam/steamapps/compatdata/3858932643/pfx/drive_c
    store: gog
redirects: []
backup:
  path: /home/niscolas/_vault/ludusavi
  ignoredGames:
    - Apex Legends
    - Barotrauma
    - Bloons TD 6
    - Borderlands 3
    - "Borderlands: The Pre-Sequel"
    - Crawl
    - Crypt of the NecroDancer
    - Darkest Dungeon
    - Deep Rock Galactic
    - Dishonored 2
    - "Don't Starve Together"
    - Doom (2016)
    - Elden Ring
    - Enter the Gungeon
    - Full Metal Furies
    - Hades
    - Heave Ho
    - Helldivers
    - Hollow Knight
    - Resident Evil Village
    - Risk of Rain 2
    - Rocket League
    - Rogue Legacy 2
    - Sifu
    - "Stick Fight: The Game"
    - Streets of Rogue
    - Sundered
    - Super Cane Magic ZERO
    - "The Witcher 3: Wild Hunt"
    - "Tiny Tina's Wonderlands"
    - Vagante
    - Wizard of Legend
  filter:
    excludeStoreScreenshots: false
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: simple
    zip:
      compression: deflate
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
restore:
  path: /home/niscolas/_vault/ludusavi
  ignoredGames: []
  sort:
    key: status
    reversed: false
scan:
  showDeselectedGames: true
  showUnchangedGames: true
  showUnscannedGames: true
cloud:
  remote:
    GoogleDrive:
      id: ludusavi-1686790409
  path: my_game_my_rules/saves-ludusavi
  synchronize: true
apps:
  rclone:
    path: /usr/bin/rclone
    arguments: ""
customGames:
  - name: Elden Ring
    files:
      - "<winAppData>/EldenRing"
    registry: []
  - name: Shadow of War
    files:
      - /home/niscolas/.local/share/Steam/steamapps/compatdata/3858932643/pfx/drive_c/users/steamuser/AppData/Local/WB Games/Shadow of War
    registry: []
