#!/usr/bin/env bash

name="bspwm"

export SCRIPTS_DIR="$HOME/scripts"
pgrep -x sxhkd > /dev/null || sxhkd &

# colorscheme {{{
theme_path="$HOME/.config/bspwm/themes/$NISCOLAS_THEME"
[[ -f "$theme_path" ]] && "$theme_path"
# }}}

# window behavior {{{
bspc config border_width 4
bspc config window_gap 16
bspc config split_ratio 0.52
# }}}

# pointer behavior {{{
bspc config focus_follows_pointer false
bspc config pointer_follows_focus true
# }}}

# monocle {{{
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle true
bspc config single_monocle false
# }}}

# (once) autostart {{{
wired &
xsetroot -cursor_name left_ptr &
blueman-applet &
nm-applet &
picom --experimental-backends &
# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
xss-lock --transfer-sleep-lock -- i3lock --nofork &
lxsession &
syncthing &
# }}}

"$SCRIPTS_DIR/notify_script_start.sh" "$name"

"$SCRIPTS_DIR/bspwm/bspwm-auto_monitor_setup.sh"
"$SCRIPTS_DIR/bspwm/bspwm-common_setup.sh"

dex --autostart --environment bspwm &

"$SCRIPTS_DIR/notify_script_success.sh" "$name"

# vim:foldmethod=marker
